<<<<<<< HEAD
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import './globals.css'

const _geist = Geist({ subsets: ["latin"] });
const _geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'OneSecMotion - Professional Photographer Mustapha Doauz',
  description: 'OneSecMotion - Professional photography by Mustapha Doauz specializing in portrait, landscape, and editorial photography.',
  icons: {
    icon: [
      {
        url: '/image/onesecmotionlogo.jpg',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/image/onesecmotionlogo.jpg',
        media: '(prefers-color-scheme: dark)',
      },
      {
        url: '/image/onesecmotionlogo.jpg',
        type: 'image/jpg+xml',
      },
    ],
    apple: '/image/onesecmotionlogo.jpg',
  },
}
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> a96824bf1c744237cb520dcc88a8ff9947a3eec1

export default function RootLayout({
  children,
}: Readonly<{
<<<<<<< HEAD
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased bg-background text-foreground`}>
        {children}
        <Analytics />
      </body>
    </html>
  )
=======
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
>>>>>>> a96824bf1c744237cb520dcc88a8ff9947a3eec1
}
